### ISSUE TITLE
Relaxing upper bound on base for the version on Hackage

### ISSUE THREAD

**Issue by larskuhtz** [gazay/gimlh#2]
It would be helpful if the change from PR #1 would be reflected in the package released on Hackage. This could be done either by releasing and uploading a new version or by just making a new "light-weight" revision on Hackage using the ["edit package information" link on the Hackage page of gmilh](http://hackage.haskell.org/package/gimlh/maintain)

**Comment by gazay** [comment]
Done, version 0.1.3.0. Thank you!
